#!/usr/bin/env bash
#Install nginx web server

sudo pt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello ALXers from Tsegbs!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
